name: kafka

include:
  - compose.kafka.consumer.yaml
  - compose.kafka.fastapi.yaml

volumes:
  pgdata:
  kafka_data:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  kafka_broker:
    container_name: kafka_broker
    image: apache/kafka:latest
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_broker:9093
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # common settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - private_network
      - public_network
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test123
    volumes:
      - ../pgdb/config:/config
    networks:
      - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/prod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  flyway:
    container_name: flyway
    build:
      context: ../flyway/
      dockerfile: Dockerfile
    restart: "no"
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/app_db
      FLYWAY_USER: dbadmin
      FLYWAY_PASSWORD: test123
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: "test123"
      FLYWAY_PLACEHOLDERS_APP_READONLY_PASSWORD: "test123"
    networks:
      # - public_network
      - private_network
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    networks:
      # - public_network
      - private_network
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ../nginx/config/kafka.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
