{
 "title": "Performance Dashboard-Comparison",
 "tags": [
  "aws",
  "performance test"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/iot-mgnt-telemetry-scale-alb/e64931d3992b1d1c"
     },
     "label": "Scale",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/iot-mgnt-telemetry-tune-alb/07e265cc453b3a85"
     },
     "label": "Tune",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/iot-mgnt-telemetry-redis-alb/98a8e1069539a5d7"
     },
     "label": "Redis",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/iot-mgnt-telemetry-kafka-alb/c4b304c52e9db8d2"
     },
     "label": "Kafka",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "ECS Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Task Count - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "label": "Scale",
     "metricName": "DesiredTaskCount",
     "metricQueryType": 1,
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-scale-cluster"
         },
         "property": { "name": "ClusterName", "type": "string" },
         "type": "operator"
        },
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-scale-service-fastapi"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'iot-mgnt-telemetry-scale-cluster' AND ServiceName = 'iot-mgnt-telemetry-scale-service-fastapi' ORDER BY SUM() ASC",
     "statistic": "Average"
    },
    {
     "label": "Tune",
     "metricName": "DesiredTaskCount",
     "metricQueryType": 1,
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-tune-cluster"
         },
         "property": { "name": "ClusterName", "type": "string" },
         "type": "operator"
        },
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-tune-service-fastapi"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'iot-mgnt-telemetry-tune-cluster' AND ServiceName = 'iot-mgnt-telemetry-tune-service-fastapi' ORDER BY SUM() ASC",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-redis-cluster",
      "ServiceName": "iot-mgnt-telemetry-redis-service-fastapi"
     },
     "label": "Redis",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-kafka-cluster",
      "ServiceName": "iot-mgnt-telemetry-kafka-service-fastapi"
     },
     "label": "Kafka",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-scale-cluster",
      "ServiceName": "iot-mgnt-telemetry-scale-service-fastapi"
     },
     "label": "Scale",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-tune-cluster",
      "ServiceName": "iot-mgnt-telemetry-tune-service-fastapi"
     },
     "label": "Tune",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-redis-cluster",
      "ServiceName": "iot-mgnt-telemetry-redis-service-fastapi"
     },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-kafka-cluster",
      "ServiceName": "iot-mgnt-telemetry-kafka-service-fastapi"
     },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Connections - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-scale-rds-pgdb"
     },
     "label": "Scale",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-tune-rds-pgdb"
     },
     "label": "Tune",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-redis-rds-pgdb"
     },
     "label": "Redis",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-kafka-rds-pgdb"
     },
     "label": "Kafka",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-scale-rds-pgdb"
     },
     "label": "Scale",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-tune-rds-pgdb"
     },
     "label": "Tune",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-redis-rds-pgdb"
     },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-kafka-rds-pgdb"
     },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "ElastiCache - Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Utilization(%) - Redis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "CacheClusterId": "iot-mgnt-telemetry-redis-redis-001",
      "CacheNodeId": "0001"
     },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "CacheClusterId": "iot-mgnt-telemetry-kafka-redis-001",
      "CacheNodeId": "0001"
     },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cache Hit - Redis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "CacheClusterId": "iot-mgnt-telemetry-redis-redis-001",
      "CacheNodeId": "0001"
     },
     "label": "Redis",
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "CacheClusterId": "iot-mgnt-telemetry-kafka-redis-001",
      "CacheNodeId": "0001"
     },
     "label": "Kafka",
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "MSK - Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU Utilization(%) - Kafka",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "iot-mgnt-telemetry-kafka-msk" },
     "metricName": "CpuSystem",
     "namespace": "AWS/Kafka",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Client Connection - Kafka",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "iot-mgnt-telemetry-kafka-msk" },
     "label": "Kafka",
     "metricName": "ClientConnectionCount",
     "namespace": "AWS/Kafka",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Task Count - Kafka-Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "label": "Kafka",
     "metricName": "DesiredTaskCount",
     "metricQueryType": 1,
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-kafka-cluster"
         },
         "property": { "name": "ClusterName", "type": "string" },
         "type": "operator"
        },
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-kafka-service-consumer"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'iot-mgnt-telemetry-kafka-cluster' AND ServiceName = 'iot-mgnt-telemetry-kafka-service-consumer' ORDER BY SUM() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - Kafka-Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-kafka-cluster",
      "ServiceName": "iot-mgnt-telemetry-kafka-service-consumer"
     },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}