name: cache

volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test123
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./pgdb/config:/config
    networks:
      # - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/cache.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
        reservations:
          cpus: "1"
          memory: 2048M

  flyway:
    container_name: flyway
    build:
      context: ./flyway/
      dockerfile: Dockerfile
    restart: "no"
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/app_db
      FLYWAY_USER: dbadmin
      FLYWAY_PASSWORD: test123
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: "test123"
      FLYWAY_PLACEHOLDERS_APP_READONLY_PASSWORD: "test123"
    networks:
      # - public_network
      - private_network
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    networks:
      # - public_network
      - private_network
    ports:
      - "6379:6379"

  fastapi01:
    container_name: fastapi01
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi02:
    container_name: fastapi02
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi03:
    container_name: fastapi03
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi04:
    container_name: fastapi04
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 256M

  fastapi05:
    container_name: fastapi05
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi06:
    container_name: fastapi06
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi07:
    container_name: fastapi07
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi08:
    container_name: fastapi08
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: cache
      DEBUG: true
      POOL_SIZE: 5
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__DB: 0
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/config/cache.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      fastapi01:
        condition: service_healthy
      # fastapi02:
      #   condition: service_healthy
      # fastapi03:
      #   condition: service_healthy
      # fastapi04:
      #   condition: service_healthy
