services:
  fastapi01:
    container_name: fastapi01
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi02:
    container_name: fastapi02
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi03:
    container_name: fastapi03
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi04:
    container_name: fastapi04
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi05:
    container_name: fastapi05
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi06:
    container_name: fastapi06
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi07:
    container_name: fastapi07
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi08:
    container_name: fastapi08
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi09:
    container_name: fastapi09
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
  fastapi10:
    container_name: fastapi10
    build:
      context: ./fastapi_kafka/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: queue
      DEBUG: true
      POOL_SIZE: 20
      MAX_OVERFLOW: 10
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
