name: queue

volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  kafka_broker:
    image: apache/kafka:latest
    container_name: kafka_broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - private_network
    ports:
      - "9092:9092" # Port for local machine connection

  kafka-worker:
    container_name: kafka_worker
    build:
      context: ./worker/
      dockerfile: Dockerfile
    command: python processor.py # Assumes your consumer logic is in processor.py
    environment:
      # Kafka Connection
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
      # Postgres Connection
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user # Assuming app_user for the worker service
      POSTGRES__PASSWORD: test123
    networks:
      - private_network
    depends_on:
      kafka_broker:
        condition: service_started # Needs Kafka to consume messages
      postgres:
        condition: service_healthy # Needs DB to write results
      flyway:
        condition: service_completed_successfully # Needs migrations to be done
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test123
    volumes:
      - ./pgdb/config:/config
    networks:
      # - public_network
      - private_network
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  flyway:
    container_name: flyway
    build:
      context: ./flyway/
      dockerfile: Dockerfile
    restart: "no"
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/app_db
      FLYWAY_USER: dbadmin
      FLYWAY_PASSWORD: test123
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: "test123"
      FLYWAY_PLACEHOLDERS_APP_READONLY_PASSWORD: "test123"
    networks:
      # - public_network
      - private_network
    depends_on:
      postgres:
        condition: service_healthy

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      APP_NAME: iot-mgnt-telemetry
      ENV: baseline
      DEBUG: true
      POSTGRES__HOST: postgres
      POSTGRES__DB: app_db
      POSTGRES__PORT: 5432
      POSTGRES__USER: app_user
      POSTGRES__PASSWORD: test123
      KAFKA__HOST: kafka_broker
      KAFKA__PORT: 9092
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/config/baseline.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      fastapi:
        condition: service_healthy
