-- V010__create_tb_device_registry.sql
------------------------------------------------------------
-- Create table app.device_registry – devices that enable tracking.
------------------------------------------------------------

SET LOCAL ROLE app_owner;

CREATE TABLE IF NOT EXISTS app.device_registry (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias           VARCHAR(64),    
    device_uuid     UUID            NOT NULL UNIQUE,
    api_key_hash    TEXT            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


------------------------------------------------------------
-- Trigger: update updated_at timestamp for any table that calls it.
------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_device_registry_set_updated_at ON app.device_registry;
CREATE TRIGGER trg_device_registry_set_updated_at
BEFORE UPDATE ON app.device_registry
FOR EACH ROW
EXECUTE FUNCTION app.fn_set_updated_at();

RESET ROLE;