-- V011__create_tb_telemetry_event.sql
------------------------------------------------------------
-- Create table app.telemetry_event
--   full historical log of all accepted telemetry events.
------------------------------------------------------------

SET LOCAL ROLE app_owner;

------------------------------------------------------------
-- Table: app.telemetry_event
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app.telemetry_event (
    id                BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid       UUID             NOT NULL,
    x_coord           DOUBLE PRECISION NOT NULL,
    y_coord           DOUBLE PRECISION NOT NULL,
    device_time       TIMESTAMPTZ      NOT NULL,
    system_time_utc   TIMESTAMPTZ      NOT NULL DEFAULT NOW()
);

------------------------------------------------------------
-- Index: last location / time-ordered queries by device
------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_telemetry_event_device_system_time_utc
    ON app.telemetry_event (device_uuid, system_time_utc DESC);

RESET ROLE;
