name: scale

include:
  - compose.scale.fastapi.yaml

volumes:
  pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../pgdb/config:/config:ro
    networks:
      # - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/prod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    mem_limit: 4g
    cpus: 2.0
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 5G
    #     reservations:
    #       cpus: "1"
    #       memory: 4G

  flyway:
    container_name: flyway
    build:
      context: ../flyway/
      dockerfile: Dockerfile
    restart: "no"
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/app_db
      FLYWAY_USER: dbadmin
      FLYWAY_PASSWORD: test123
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: "test123"
      FLYWAY_PLACEHOLDERS_APP_READONLY_PASSWORD: "test123"
    networks:
      # - public_network
      - private_network
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ../nginx/config/scale.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
